language: go
sudo: false
addons:
  apt:
    packages:
      - redis-server
      - docker-ce
cache:
  directories:
    - $GOPATH/pkg
    - $GOPATH/bin
services:
  - redis-server
env:
  global:
    - GO111MODULE=on
    - GO_FOR_RELEASE=1.x
    - CGO_ENABLED=0
go:
  - 1.x
  - tip
install:
  - export GOCACHE=$GOPATH/pkg/cache
  - make testdeps
script:
  - make coverage
  - go build -o video-transcoding-api
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - travis-scripts/docker.bash
deploy:
  - provider: script
    skip_cleanup: true
    script: travis-scripts/deploy.bash dev-stg
    on:
      repo: NYTimes/video-transcoding-api
      branch: master
      go: 1.x
  - provider: script
    skip_cleanup: true
    script: travis-scripts/deploy.bash prd
    on:
      repo: NYTimes/video-transcoding-api
      tags: true
      go: 1.x
notifications:
  email: false
